services:
  app:
    image: nginx:alpine
    container_name: app-template
    restart: always
    networks:
      - proxy
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-template.rule=Host(`app-template.valhallala.com`)"
      - "traefik.http.routers.app-template.entrypoints=websecure"
      - "traefik.http.routers.app-template.tls.certresolver=letsencrypt"

networks:
  proxy:
    external: true
